blueprint:
  name: Monitoring of CO2 Sensors
  description: Notifies when CO2 levels exceed a predefined threshold.
  domain: automation
  input:
    co2_sensors:
      name: Monitor CO2 Sensors
      description: CO2 sensors to monitor for exceeding the threshold.
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
          multiple: true
    threshold:
      name: Threshold
      description: The CO2 level that should be exceeded to trigger a notification.
      default: 1000
      selector:
        number:
          min: -50
          max: 5000
          step: 1

trigger:
  platform: numeric_state
  entity_id: !input co2_sensors
  above: !input threshold

action:
- service: persistent_notification.create
  data:
    message: "CO2 level of {{ trigger.to_state.attributes.friendly_name }} has exceeded the threshold of {{ threshold }} ppm."
    title: "CO2 Warning"
    notification_id: "co2_warning_{{ trigger.to_state.entity_id }}"

- alias: 'CO2 Level Normal'
  trigger:
    platform: numeric_state
    entity_id: !input co2_sensors
    below: !input threshold
  action:
  - service: persistent_notification.dismiss
    data_template:
      notification_id: "co2_warning_{{ trigger.to_state.entity_id }}"
