blueprint:
  name: Monitoring of CO2 Sensors
  description: Notifies when CO2 levels exceed a predefined threshold.
  domain: automation
  input:
    co2_sensors:
      name: Monitor CO2 Sensors
      description: CO2 sensors to monitor for exceeding the threshold.
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
          multiple: true
    threshold:
      name: Threshold
      description: The CO2 level that should be exceeded to trigger a notification.
      default: 1000
      selector:
        number:
          min: -50
          max: 5000
          step: 1
    actions:
      name: Actions
      description: The CO2 level of {{entity_name}} has exceeded the threshold of {{defined_threshold}} ppm.
      selector:
        action: {}

variables:
  defined_threshold: !input threshold

trigger:
  platform: numeric_state
  entity_id: !input co2_sensors
  above: !input threshold

action:
- variables:
    entity_name: "{{ trigger.to_state.attributes.friendly_name }}"
- choose: []
  default: !input 'actions'
