blueprint:
  name: Überwachung von CO2-Sensoren
  description: Benachrichtigt, wenn CO2-Werte einen festgelegten Schwellenwert überschreiten.
  domain: automation
  input:
    co2_sensors:
      name: CO2-Sensoren überwachen
      description: Die CO2-Sensoren, die auf überschreitung des Schwellenwerts überwacht werden sollen.
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
          multiple: true
    threshold:
      name: Schwellenwert
      description: Der CO2-Wert, der überschritten werden soll, um benachrichtigt zu werden.
      default: 1000
      selector:
        number:
          min: -50
          max: 5000
          step: 1
    actions:
      name: Actions
      description: Der CO2-Wert von {{entity_name}} hat den Schwellenwert von {{defined_threshold}} ppm überschritten.
      selector:
        action: {}

variables:
  defined_threshold: !input threshold

trigger:
  platform: numeric_state
  entity_id: !input co2_sensors
  above: !input threshold

action:
- variables:
    entity_name: "{{ trigger.to_state.attributes.friendly_name }}"
- choose: []
  default: !input 'actions'
